server:
  port: 8082

spring:
  application:
    name: parking-service
  data:
    mongodb:
      uri: ${PARKING_MONGODB_URI:mongodb://localhost:27018/parkingservicedb}

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${PARKING_SERVICE_INSTANCE_HOSTNAME:parking-service}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name:parking-service}
  server:
    port: 8082
